--- 
- 
  gather_facts: false
  hosts: vjhvf
  name: vargant
  tasks: 
    - 
      name: cd_vagrant1
      win_command: "cd C:\\HashiCorp\\Vagrant\\bin\\"
    - 
      name: "add image"
      win_command: "vagrant.exe box add ubuntu/trusty64"
- 
  gather_facts: false
  hosts: vjhvf
  name: "vargant up"
  tasks: 
    - 
      name: "vagrant init"
      win_command: "vagrant.exe init ubuntu/trusty64"
    - 
      name: "vagrant up"
      win_command: "vagrant.exe up ubuntu/trusty64"
