--- 
- 
  gather_facts: false
  hosts: vjhvf
  name: vargant
  tasks: 
    - 
      name: "add image"
      win_psexec: 
        command: "vagrant.exe box add ubuntu/trusty64"
        executable: "C:\\HashiCorp\\Vagrant\\bin\\"
    - 
      name: "vagrant init"
      win_psexec: 
        command: "vagrant.exe box add ubuntu/trusty64"
        executable: "C:\HashiCorp\Vagrant\bin\"
- 
  gather_facts: false
  hosts: vjhvf
  name: "vargant up"
  tasks: 
    - 
      name: "vagrant up"
      win_psexec: 
        command: "vagrant.exe up ubuntu/trusty64"
        executable: "C:\HashiCorp\Vagrant\bin\"
