---

- name: vargant
  hosts: vjhvf
  gather_facts: false
  
 # tasks:

    #- name: add image1
     # win_psexec: 
      #  command: box add ubuntu/trusty64
       # executable: C:\HashiCorp\Vagrant\bin\vagrant.exe

  #  - name: vagrant init
   #   win_psexec:
   #     command: init
    #    executable: C:\HashiCorp\Vagrant\bin\vagrant.exe

#- name: vargant up
 # hosts: vjhvf
  #gather_facts: false
  tasks:

   - name: vagrant up
     win_psexec:  
       command: up
       executable: C:\HashiCorp\Vagrant\bin\vagrant.exe

