---

- name: vargant
  hosts: vjhvf
  gather_facts: false
  
  tasks:

    - name: add image1
      win_psexec: 
        command: C:\HashiCorp\Vagrant\bin\vagrant.exe vagrant box add ubuntu/trusty64 
       # executable: C:\HashiCorp\Vagrant\bin\vagrant.exe box add ubuntu/trusty64

    - name: vagrant init
      win_psexec:
        command: vagrant.exe box init ubuntu/trusty64
        executable: C:\HashiCorp\Vagrant\bin\vagrant.exe

- name: vargant up
  hosts: vjhvf
  gather_facts: false

  
  tasks:

   - name: vagrant up
     win_psexec:  
       command: vagrant.exe up ubuntu/trusty64
       executable: C:\HashiCorp\Vagrant\bin\vagrant.exe
