---

- name: vargant
  hosts: vjhvf
  gather_facts: false
  
  tasks:

    - name: chdir
      win_psexec: 
        chdir: C:\HashiCorp\Vagrant\bin\
      #  executable: C:\HashiCorp\Vagrant\bin\vagrant.exe

    - name: vagrant init
      win_psexec:
        chdir: C:\HashiCorp\Vagrant\bin\
        command: init
        executable: C:\HashiCorp\Vagrant\bin\vagrant.exe

- name: vargant up
  hosts: vjhvf
  gather_facts: false
  tasks:

   - name: vagrant up
     win_psexec:  
       command: up
       executable: C:\HashiCorp\Vagrant\bin\vagrant.exe

